# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bozkatzailea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('erabiltzailea_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izenburua', models.CharField(max_length=255)),
                ('zuzendaria', models.CharField(max_length=255)),
                ('urtea', models.CharField(max_length=4)),
                ('generoa', models.CharField(max_length=2)),
                ('sinopsia', models.TextField()),
                ('bozkak', models.IntegerField(default=0)),
            ],
        ),
    ]
