# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-18 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmaBozkatzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bozkak', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bozkatzailea',
            name='erabiltzailea_id',
        ),
        migrations.AddField(
            model_name='bozkatzailea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bozkatzailea',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='filmabozkatzailea',
            name='bozkatzailea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Bozkatzailea'),
        ),
        migrations.AddField(
            model_name='filmabozkatzailea',
            name='filma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Filma'),
        ),
    ]
