# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-18 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20230418_1001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmabozkatzailea',
            unique_together=set([('filma', 'bozkatzailea')]),
        ),
    ]
